//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBMUSTERILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBMUSTERILER()
        {
            this.TBSATISLAR = new HashSet<TBSATISLAR>();
        }
    
        public int MUSTERIID { get; set; }
        [Required(ErrorMessage ="Bu Alaný Boþ Býrakamazsýnýz...")]
        [StringLength(50,ErrorMessage ="En Fazla 50 Karakterlik Ýsim Girin...")]
        public string MUSTERIAD { get; set; }
        public string MUSTERISOYAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBSATISLAR> TBSATISLAR { get; set; }
    }
}
